# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161017_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='created',
        ),
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
    ]
