# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161017_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.URLField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
