# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161017_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='short_url',
            field=models.CharField(default='aa', max_length=40),
            preserve_default=False,
        ),
    ]
