# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_link_short_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Link')),
            ],
        ),
    ]
