# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
